// Generated by tygo.  DO NOT EDIT!

package main

/*
type Corpus enum {
	UNIVERSAL = 0
	WEB       = 1
	IMAGES    = 2
	LOCAL     = 3
	NEWS      = 4
	PRODUCTS  = 5
	VIDEO     = 6
}

type Vector2 object {
	X float32
	Y fixedpoint<1, -10>
	B []byte
	S string
	E Corpus
	P *GoType
}

type Fighter_Part1 object {
	Pos     *Vector2
	IsAwake bool
	Hp      float32
	Poss    map[int32]*Vector2
	Posi    map[int32]float32
	Posl    []*Vector2
	Posll   [][]*Vector2
	Pyl     []*GoType
	Pyd     map[int32]*GoType
	Pyv1    variant<int32, *GoType>
	Pyv2    variant<int32, *GoType>
}

type Fighter_Part2 object {
	Fighter_Part1
	Fl []float32
	Bl [][]byte
	Sl []string
	Bd map[string][]byte
	Sd map[int32]string
	El []Corpus
	Ed map[int32]Corpus
	Ll [][]float32
}

type Fighter object {
	Fighter_Part2
	V0  variant<int32, float32, []byte, *Vector2>
	V1  variant<int32, float32, []byte, *Vector2>
	V2  variant<int32, float32, []byte, *Vector2>
	V3  variant<int32, float32, []byte, *Vector2>
	V4  variant<int32, float32, []byte, *Vector2>
	Vl  []variant<int32, fixedpoint<3, 0>, string, *Vector2>
	Vd  map[int32]variant<Corpus, float64, string, *Vector2>
	Ld  map[int32][]variant<Corpus, float64, string, *Vector2>
	Fld map[int32][]float32
	Dd  map[int32]map[int32]variant<int32, Corpus, float64, string, *Vector2>
	Fdd map[int32]map[int32]float32
	Nv  variant<nil, int32>
	Lv  variant<int32, []variant<float32, string>>
	Flv variant<int32, []float32>
	Dv  variant<int32, map[int32]variant<float32, string>>
	Fdv variant<int32, map[int32]float32>
	RPG(*Fighter, variant<nil, int32>, fixedpoint<3, 0>) *Vector2
	GPR(map[int32]variant<Corpus, float64, string, *Vector2>) (*Fighter, int32)
}

*/